CREATE TABLE users (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    role VARCHAR2(50),
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id)
);


CREATE TABLE project (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    status VARCHAR2(50),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id)
);


CREATE TABLE project_user (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    project_id NUMBER(19,0),
    user_id NUMBER(19,0),
    role VARCHAR2(50),
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);


INSERT INTO users (email, password, name, role, is_deleted, created_at, updated_at)
VALUES ('user1@test.com', 'hashed_pwd', '개발자A', 'USER', 0, SYSDATE, SYSDATE);

INSERT INTO users (email, password, name, role, is_deleted, created_at, updated_at)
VALUES ('user2@test.com', 'hashed_pwd', '개발자B', 'USER', 0, SYSDATE, SYSDATE);

-- 프로젝트 생성 (1~4번은 유저1용, 5번은 유저2용)
INSERT INTO project (title, description, status, start_date, end_date, is_deleted, created_at, updated_at)
VALUES ('스프링부트 프로젝트', '설명1', 'ACTIVE', TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-06-01', 'YYYY-MM-DD'), 0, SYSDATE, SYSDATE);

INSERT INTO project (title, description, status, start_date, end_date, is_deleted, created_at, updated_at)
VALUES ('리액트 클론 프로젝트', '설명2', 'ACTIVE', TO_DATE('2026-02-01', 'YYYY-MM-DD'), TO_DATE('2026-07-01', 'YYYY-MM-DD'), 0, SYSDATE, SYSDATE);

INSERT INTO project (title, description, status, start_date, end_date, is_deleted, created_at, updated_at)
VALUES ('인프라 구축 프로젝트', '설명3', 'COMPLETED', TO_DATE('2026-03-01', 'YYYY-MM-DD'), TO_DATE('2026-04-01', 'YYYY-MM-DD'), 0, SYSDATE, SYSDATE);

INSERT INTO project (title, description, status, start_date, end_date, is_deleted, created_at, updated_at)
VALUES ('보안 고도화 작업', '설명4', 'ARCHIVED', TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-05-01', 'YYYY-MM-DD'), 0, SYSDATE, SYSDATE);

INSERT INTO project (title, description, status, start_date, end_date, is_deleted, created_at, updated_at)
VALUES ('타 유저 프로젝트', '설명5', 'ACTIVE', TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-03-01', 'YYYY-MM-DD'), 0, SYSDATE, SYSDATE);


INSERT INTO project_user (project_id, user_id, role, is_deleted) VALUES (1, 1, 'OWNER', 0);
INSERT INTO project_user (project_id, user_id, role, is_deleted) VALUES (2, 1, 'MEMBER', 0);
INSERT INTO project_user (project_id, user_id, role, is_deleted) VALUES (3, 1, 'MEMBER', 0);
INSERT INTO project_user (project_id, user_id, role, is_deleted) VALUES (4, 1, 'MEMBER', 0);
INSERT INTO project_user (project_id, user_id, role, is_deleted) VALUES (5, 2, 'OWNER', 0);

COMMIT;