### 태그 생성
POST http://localhost:8080/api/tag
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "태그 이름",
  "color": "태그 색"
}

### 태그 단건 조회
GET http://localhost:8080/api/tags/1
Authorization: Bearer {{accessToken}}

### 태그 목록 조회
GET http://localhost:8080/api/tags
Authorization: Bearer {{accessToken}}

### 태그 수정
PUT http://localhost:8080/api/tags/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "수정된 태그 이름",
  "color": "수정된 태그 색"
}

### 태그 삭제
DELETE http://localhost:8080/api/tags/1
Authorization: Bearer {{accessToken}}
