### 작업 생성
POST http://localhost:8080/api/task
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "projectId": 1,
  "title": "작업 이름",
  "description": "작업 설명",
  "status": "TODO",
  "priority": "HIGH",
  "dueDate": "2026-07-07",
  "tagIds": [1],
  "assigneeId": 41
}


### 작업 상태 목록 조회
GET http://localhost:8080/api/tasks/status
Authorization: Bearer {{accessToken}}


### 작업 상태 목록 조회
GET http://localhost:8080/api/tasks/priority
Authorization: Bearer {{accessToken}}


### 칸반보드 작업 목록 조회
GET http://localhost:8080/api/tasks/kanban?projectId=1
Authorization: Bearer {{accessToken}}


### 작업 목록 조회 (페이지네이션: page, size, sort)
GET http://localhost:8080/api/tasks?projectId=1&title=작업&assigneeId=0&status=ALL&priority=HIGH&page=0&size=5&sort=dueDate,ACS
Authorization: Bearer {{accessToken}}


### 작업 상세 조회
GET http://localhost:8080/api/tasks/1
Authorization: Bearer {{accessToken}}